name: Update Points

on:
  schedule:
    - cron: '*/15 * * * *' 
  workflow_dispatch:

jobs:
  calc-points:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      uses: actions/checkout@v2

    - name: Make API call to update leaderboard
      run: |
        curl -X GET https://eurocaster.vercel.app/api/conf/calculatepoints -H "Authorization: Bearer $BEARER_TOKEN"
